sudo: required
language: java
dist: trusty



cache:
  directories:
  - $HOME/.m2

script:
 - robot test_cases/*.robot





before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
 - sudo apt-get install -y libnss3 libgconf-2-4
 - sudo python -m pip install robotframework
 - sudo pip install --upgrade --pre robotframework-selenium2library

before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


after_script:
  - cat target/surefire-reports/TestSuite.txt

notifications:
  email:
    recipients:
      - munsei@binary.com
      - ridho@binary.com
      - fahad@binary.com
      - yatin@binary.com
    on_success: never
    on_failure: yes